// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttoooscxvizgbdlgoupd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0b29vc2N4dml6Z2JkbGdvdXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzA1NzQsImV4cCI6MjA2MzQwNjU3NH0.XZ_IN08aXW4ydNrTtNdBSMWfPsmZiZ9l-SFpilS04Eg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);